### PR TITLE
Added tests for EventFragment and moved FRC implementation from EventFragment into a repository

### PR DESCRIPTION
**Pull request by johnGachihi**

### CODE REVIEW

**Comment by wangerekaharun** [comment]
Gone through your changes @johnGachihi.

In the `WifiDetailsRepoImpl` you are using a `suspendCancellableCoroutine` whereas in PR #52 we introduced `runCatching` top level function for wrapping all Firebase calls. Then again there is a couple of differences in how you are exposing data to the view. We shall have to discuss this so that we maintain consistency across all layers

**Review by wangerekaharun — COMMENTED** [review]
Gone through your changes @johnGachihi.

In the` WifiDetailsRepoImpl` you are using a `suspendCancellableCoroutine `whereas in PR #52 we introduced `runCatching` top level function for wrapping all Firebase calls. Then again there is a couple of differences in how you are exposing data to the view. We shall have to discuss this so that we maintain consistency across all layers

**Comment by johnGachihi** [comment]
About the `WifiDetailsRepoImpl`, is this a better approach:
[https://gist.github.com/johnGachihi/6590de6e845e2089eca33e53e426bc9d](https://gist.github.com/johnGachihi/6590de6e845e2089eca33e53e426bc9d)

**Comment by wangerekaharun** [comment]
@johnGachihi we have` .await()` from `ktx` so you can just use that one. You can cross check the implementation on other repos too

**Comment by johnGachihi** [comment]
Nice. I didn't know .await() existed. So doesn't that mean the functions in [this file](https://github.com/droidconKE/droidconKE2019App/blob/master/app/src/main/java/com/android254/droidconke19/utils/firestore.kt) are unnecessary

**Comment by johnGachihi** [comment]
> @johnGachihi we have` .await()` from `ktx` so you can just use that one. You can cross check the implementation on other repos too

Is this better: [https://gist.github.com/johnGachihi/6590de6e845e2089eca33e53e426bc9d](https://gist.github.com/johnGachihi/6590de6e845e2089eca33e53e426bc9d).
Or have I made it worse

**Comment by michaelbukachi** [comment]
Hi @johnGachihi I've just gone through the snippet and noticed `FRC`. I think using such initials tends to bring more confusion. Names should be as clear as possible so I suggest you change that. Also, why are you giving the `WifiDetailsModel` a body. You should create an `object` instead and put the extra logic there. The model should contain the fields only.

**Comment by johnGachihi** [comment]
I have edited it @michaelbukachi 
[https://gist.github.com/johnGachihi/6590de6e845e2089eca33e53e426bc9d](https://gist.github.com/johnGachihi/6590de6e845e2089eca33e53e426bc9d)

**Comment by michaelbukachi** [comment]
Cool. Looks better. 
One last thing. You should rename `createUsingFirebaseRemoteConfigData` to just `create` since `WifiDetailsModelFactory.create(firebaseRemoteConfig)` paints a clear picture of what is going on.

**Comment by wangerekaharun** [comment]
The functions in that file were way long before ktx was added so now they are  not in use. We are still doing the cleanup to remove unused code

**Comment by wangerekaharun** [comment]
One question to @michaelbukachi  and @johnGachihi . Now that @johnGachihi implemementation exposes the sealed class to the view, should we do a re-write to all the viewmodel layers to follow the same?

**Comment by johnGachihi** [comment]
I took that approach because it only requires one livedata for all states of data. The current approach requires livedata for each state of data. For example, for organizers data in `AboutViewModel` there are
- `organizersLiveData`    for    successful fetch
- `organizersError`          for    unsuccessful fetch

This means the view has to observe the two livedata to know the state of the organizers data. But since the data can't take more than one state (e.g the fetch can't be both successful and unsuccessful), only one of the two livedata will emit data in the lifetime of the view. The other livedata is observed though it never emits a value. If the data had more states e.g loading then there would be more livedata the view observes though they never emit a value in the view's lifetime

With approach I took the view only needs to listen to one livedata.
But I see `FirebaseResult` should be renamed to lack the word `Firebase` if it is to be exposed to views.

**Comment by michaelbukachi** [comment]
But one state carries the message and the other carries the result. Since the types are not the same, I think it's okay to have different livedata. The only change I would make is having one LiveData for handling all errors. We cannot use `Result` as name since it's already used in Kotlin.

**Comment by wangerekaharun** [comment]
Using one LiveData for all errors will bring exceptions lets say for example we have one error before then try to update the value with another error. Not sure if the behavior is same with LiveData but for MediatorLiveData you cannot do the same

**Comment by michaelbukachi** [comment]
I'm lost :sweat_smile: . Could you share a snippet to demonstrate this?

**Comment by johnGachihi** [comment]
@wangerekaharun I not sure I understood correctly but is this what you meant:
```
livedata.setValue(FirebaseResult.Error("error") // Observer will be updated
...
livedata.setValue(FirebaseResult.Error("error") // Observer will not be updated 
                                                // since value set  is the same as previous one
```

**Comment by wangerekaharun** [comment]
So for example this [Original File](https://github.com/droidconKE/droidconKE2019App/blob/master/app/src/main/java/com/android254/droidconke19/viewmodels/SessionDataViewModel.kt) has a couple of  livedata for error then as to my understanding of having one error for livedata checkout this [gist](https://gist.github.com/wangerekaharun/6cbd13041ecafec81a3c2c29f4b928cb). @michaelbukachi  let me know if this is what your were saying

**Comment by wangerekaharun** [comment]
@johnGachihi  see in my gist the second setting value for the error livedata will cause an exception. Unless the behaviour changed, cause i tried the same back in early 2018 and was getting exceptions

**Comment by johnGachihi** [comment]
I can't access the gist. The link is taking me to a 404

**Comment by wangerekaharun** [comment]
> I can't access the gist. The link is taking me to a 404

Fixed

**Comment by michaelbukachi** [comment]
@wangerekaharun Yes that's what I meant. Just all exceptions are delivered as strings and delivered to the view for displaying in Snackbar/Toast have multiple liveData just makes a bit repetitive.

**Comment by wangerekaharun** [comment]
> @wangerekaharun Yes that's what I meant. Just all exceptions are delivered as strings and delivered to the view for displaying in Snackbar/Toast have multiple liveData just makes a bit repetitive.

Let me do a sample and see if there will be any issues especially on rotation change. There is that exception where lets say we have an error in method 1 and you update again to set value in method 2 when there is also an error, you get this exception 

> If the given LiveData is already added as a source but with a different Observer, IllegalArgumentException will be thrown.

**Comment by wangerekaharun** [comment]
@johnGachihi  You can now commit all changes suggested then we merge the PR

**Comment by johnGachihi** [comment]
Including the changes on the livedata?

**Comment by wangerekaharun** [comment]
No the others. Will test on the Livedata part

**Comment by johnGachihi** [comment]
Alright

**Comment by michaelbukachi** [comment]
> @johnGachihi You can now commit all changes suggested then we merge the PR

Finally. Now, I can go play some games :laughing: .

**Review by wangerekaharun — APPROVED** [review]

**Pull request merged**
